alias cat='bat'
alias cl='clear'
alias cz='chezmoi'
alias df='df -h'
alias du='du -h'
alias grep='grep --color=always'
alias less='less -FSRXc'
alias ll='ls -FlAhp --color=always'
alias lo='logout'
alias mkdir='mkdir -pv'
alias numFiles='echo $(ls -1 | wc -l)'
alias path='echo -e ${PATH//:/\\n}'
alias td='date +"%Y%m%d"'
alias ts='date +"%Y%m%d%H%M%S"'
alias vi='vim'
alias yd='date -d "1 day ago" +"%Y%m%d"'
