Vagrant.configure(2) do |config|
  # install minimum required packages before box's own provisioning is done
  config.vm.provision "shell", path: "~/.vagrant.d/scripts/provision"

  # always map these directories
  config.vm.synced_folder "c:\\tools", "/tools"
  config.vm.synced_folder "c:\\Users\\crogers\\.m2", "/root/.m2"
end
