#!/usr/bin/env bash
# default applied to all boxes; before the box's own provisioning is done

# prevent dialogs and use default values instead
export DEBIAN_FRONTEND=noninteractive

USER="vagrant"
HOME_DIR="/home/$USER"

# update everything
apt-get update > /dev/null

# install these basic required packages
apt-get -y install tmux vim git-core ruby

# install tmux session manager - https://github.com/tmuxinator/tmuxinator
gem install tmuxinator

# install tmux plugin manager - https://github.com/tmux-plugins/tpm
su -c "git clone https://github.com/tmux-plugins/tpm $HOME_DIR/.tmux/plugins/tpm" $USER

# switch to vagrant user and pull down copy of my preferred dot files
su -c "git clone https://github.com/wufpack00/dotfiles.git" $USER

# switch to vagrant user and execute script to setup dot files
su -c "cd $HOME_DIR/dotfiles && ./bin/bootstrap.sh" $USER

# switch to vagrant user and pull down helper scripts
su -c "curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash >> $HOME_DIR/.git-completion.bash" $USER
su -c "curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh >> $HOME_DIR/.git-prompt.sh" $USER 
